---
title: "DNAConcentrations"
author: "ErikaGanda"
output: html_document
---

```{r}
#Data File: DNAconcentrations
library(ggplot2)
library(dplyr)
library(emmeans)
library(multcompView)

#Read Data
AllData <- read.table("DNAconcentrations.txt", sep="\t",  fill = TRUE, header=TRUE)
dim (AllData)

#Getting All variables and all levels within each

#Summary Statistics
NanodropConc.summary <- AllData %>%
  group_by(VariableKit,VariableSampleType) %>%
  summarize(mean_NanodropConc=mean(NanodropConc,na.rm=T),
            st_dev=sd(NanodropConc,na.rm=T),
            n_missing=sum(is.na(NanodropConc)),
            n_total=n())
write.table (NanodropConc.summary, "NanodropConc.summary.txt", sep="\t" ) 

Nanodrop260280.summary <- AllData %>%
  group_by(VariableKit,VariableSampleType) %>%
  summarize(mean_Nanodrop260280k=mean(Nanodrop260280,na.rm=T),
            st_dev=sd(Nanodrop260280,na.rm=T),
            n_missing=sum(is.na(Nanodrop260280)),
            n_total=n())
write.table (Nanodrop260280.summary, "Nanodrop260280.summary.txt", sep="\t" ) 

QuantiT.summary <- AllData %>%
  group_by(VariableKit,VariableSampleType) %>%
  summarize(mean_QuantiT=mean(QuantiT,na.rm=T),
            st_dev=sd(QuantiT,na.rm=T),
            n_missing=sum(is.na(QuantiT)),
            n_total=n())
write.table (QuantiT.summary, "QuantiT.summary.txt", sep="\t" ) 
```

```{r}
sessionInfo()
```